blank_issues_enabled: false
contact_links:
  - name: Support forum
    url: https://wordpress.org/support/plugin/custom-permalinks/
    about: Questions and help with setting up the plugin.
  - name: Premium support
    url: https://www.custompermalinks.com/contact-us/
    about: One-on-one email support for Custom Permalinks Premium users.
